# config/packages/fos_user.yaml
fos_user:
  db_driver: orm # other valid values are 'mongodb' and 'couchdb'
  firewall_name: main
  user_class: App\Entity\User
  from_email:
    address: "admin@admin.com"
    sender_name: "Building Collective"
#  registration:
#    confirmation:
#      template: 'email/welcome.html.twig'
#      from_email:
#        address: "info@building.com"
#        sender_name: "Registration Web"
  service:
    mailer: fos_user.mailer.noop